---
title: "Time_Series_R_Testing"
output: html_document
---

```{r}
summary(coagulation)
```
Concatenation, Five-number summary, STD
```{r}
# Getting the data
data.1=c(35, 8, 10, 23, 42)

# Getting the summary
summary(data.1)
```

```{r}
# Getting the mean
print(mean(data.1))

# Getting the std
print(sd(data.1))
```

Working with datasets
```{r}
# Getting the data and histogram
small.size.dataset=c(91,49,76,112,97,42,70, 100, 8, 112, 95, 90, 78, 62, 56, 94, 65, 58, 109, 70, 109, 91, 71, 76, 68, 62, 134, 57, 83, 66)
hist(small.size.dataset, xlab='My data points', main='Histogram of my data', freq=F, col='green', breaks=10)  # F just means False and breaks means the bin width
lines(density(small.size.dataset), col='red', lwd=5)
```

Scatterplot
```{r}
# Setting seed
set.seed(2016)

# Simulating test courses
Test_1_scores=round(rnorm(50, 78, 10))  # Data points, average, std
Test_2_scores=round(rnorm(50, 78, 14))

# Seeing Test_1_scores
Test_1_scores
```
```{r}
# Seeing Test_2_scores
Test_2_scores
```
```{r}
# Plotting bivariate test scores
plot(Test_2_scores~Test_1_scores, main='Test scores for two exams (50 students)', xlab='Test_1_scores', ylab='Test 2 scores', col='blue')
```










